// Package version is auto-generated at build-time
package version

// Default build-time variable for library-import.
// This file is overridden on build with build-time informations.
const (
	Version string = "1.0.3"
)

// AUTOGENERATED FILE; see hack/.go-autogen
