// Package version is auto-generated at build-time
package version

// Default build-time variable for library-import.
// This file is overridden on build with build-time informations.
const (
	Version string = "0.28"
)

// AUTOGENERATED FILE; see hack/make/.go-autogen
